### ISSUE TITLE
Add Examples to Sphinx

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT-examples#11]
- [x] Map from samples
- [x] Map from density
- [x] Monotone Regression
- [x] Install from Conda
- [x] Quick start (C++/Python/Matlab)

**Comment by dannys4** [comment]
Ack, I mistook this as the other repository, sorry.

**Comment by rubiop** [comment]
In the Tutorials I think we need to include links to sources for python and other languages, maybe with instruction of how to compile them as a notebooks
