### ISSUE TITLE
Complete tutorial page in the documentation

### ISSUE THREAD

**Issue by rubiop** [MeasureTransport/MParT-examples#36]
There is some confusion with issue titles but I think there is no issue regarding the [tutorial page](https://measuretransport.github.io/MParT/source/tutorials/index.html). 

Python notebooks need to be rendered and I think we should include links to sources for python and other languages, maybe with instruction of how to compile them as a notebooks

**Comment by bonh** [comment]
We could use [cards](https://sphinx-design.readthedocs.io/en/latest/cards.html#clickable-cards) from `sphinx-design`; clickable and with a preview image for every example we want to include on the website. 

Links to source files is a good idea. We could add the links as part of the markdown description to the top of every python notebook.

**Comment by mparno** [comment]
See MParT [pull request #217](https://github.com/MeasureTransport/MParT/pull/217)
