### ISSUE TITLE
clean up matlab examples

### ISSUE THREAD

**Issue by bonh** [MeasureTransport/MParT-examples#5]
- [ ] There is an extra license file here: https://github.com/MeasureTransport/MParT-examples/blob/4ce9bad5c9be8e38240f2579bc4afe732aa7da22/examples/matlab/LICENSE.txt. Is that required for matlab bindings or is a top level license file sufficient?
- [ ] Should that file be version controlled: https://github.com/MeasureTransport/MParT-examples/blob/4ce9bad5c9be8e38240f2579bc4afe732aa7da22/examples/matlab/BananaSamples_norm.txt?

**Comment by mparno** [comment]
As for the license, I'm guessing that's a remnant of the license we need to include for `mexplus`.   A top-level license file for the entire examples repository should be sufficient.

**Comment by bonh** [comment]
The top level license is back.

**Comment by rubiop** [comment]
Hi @bonh my plan is to reformulated all the matlab examples exactly in the same way than other notebooks once we will agree on the content. The format haven't been decided yet but might be live matlab script format (.mlx) such that we will able to mix code and text exactly in the same way than python notebooks.

**Comment by bonh** [comment]
Sounds good! :+1:
